export const ROUTES = {
  HOME: 'HOME' as const,
  //
  FORM_KEYBOARD_AVOIDING_VIEW: 'FORM_KEYBOARD_AVOIDING_VIEW' as const,
  FORM_KEYBOARD_AWARE_SCROLL_VIEW: 'FORM_KEYBOARD_AWARE_SCROLL_VIEW' as const,
  FORM_IQ_KEYBOARD_MANAGER_AND_ADJUST_RESIZE: 'FORM_IQ_KEYBOARD_MANAGER+ADJUST_RESIZE' as const,
  FORM_AVOID_SOFT_INPUT_MODULE: 'FORM_AVOID_SOFT_INPUT_MODULE' as const,
  FORM_AVOID_SOFT_INPUT_VIEW: 'FORM_AVOID_SOFT_INPUT_VIEW' as const,
  //
  BOTTOM_SHEET_IQ_KEYBOARD_MANAGER_AND_ADJUST_RESIZE: 'BOTTOM_SHEET_IQ_KEYBOARD_MANAGER+ADJUST_RESIZE' as const,
  BOTTOM_SHEET_AVOID_SOFT_INPUT_MODULE: 'BOTTOM_SHEET_AVOID_SOFT_INPUT_MODULE' as const,
  BOTTOM_SHEET_AVOID_SOFT_INPUT_VIEW: 'BOTTOM_SHEET_AVOID_SOFT_INPUT_VIEW' as const,
  BOTTOM_SHEET_KEYBOARD_AVOIDING_VIEW: 'BOTTOM_SHEET_KEYBOARD_AVOIDING_VIEW' as const,
  //
  MODAL_IQ_KEYBOARD_MANAGER_AND_ADJUST_RESIZE: 'MODAL_IQ_KEYBOARD_MANAGER_AND_ADJUST_RESIZE' as const,
  MODAL_KEYBOARD_AVOIDING_VIEW: 'MODAL_KEYBOARD_AVOIDING_VIEW' as const,
  MODAL_KEYBOARD_AWARE_SCROLL_VIEW: 'MODAL_KEYBOARD_AWARE_SCROLL_VIEW' as const,
  MODAL_AVOID_SOFT_INPUT_MODULE: 'MODAL_AVOID_SOFT_INPUT_MODULE' as const,
  MODAL_AVOID_SOFT_INPUT_VIEW: 'MODAL_AVOID_SOFT_INPUT_VIEW' as const,
  //
  MODAL_BOTTOM_SHEET_IQ_KEYBOARD_MANAGER_AND_ADJUST_RESIZE: 'MODAL_BOTTOM_SHEET_IQ_KEYBOARD_MANAGER+ADJUST_RESIZE' as const,
  MODAL_BOTTOM_SHEET_AVOID_SOFT_INPUT_MODULE: 'MODAL_BOTTOM_SHEET_AVOID_SOFT_INPUT_MODULE' as const,
  MODAL_BOTTOM_SHEET_AVOID_SOFT_INPUT_VIEW: 'MODAL_BOTTOM_SHEET_AVOID_SOFT_INPUT_VIEW' as const,
  MODAL_BOTTOM_SHEET_KEYBOARD_AVOIDING_VIEW: 'MODAL_BOTTOM_SHEET_KEYBOARD_AVOIDING_VIEW' as const,
  //
  PORTAL_KEYBOARD_AVOIDING_VIEW: 'PORTAL_KEYBOARD_AVOIDING_VIEW' as const,
  PORTAL_KEYBOARD_AWARE_SCROLL_VIEW: 'PORTAL_KEYBOARD_AWARE_SCROLL_VIEW' as const,
  PORTAL_IQ_KEYBOARD_MANAGER_AND_ADJUST_RESIZE: 'PORTAL_IQ_KEYBOARD_MANAGER_AND_ADJUST_RESIZE' as const,
  PORTAL_AVOID_SOFT_INPUT_MODULE: 'PORTAL_AVOID_SOFT_INPUT_MODULE' as const,
  PORTAL_AVOID_SOFT_INPUT_VIEW: 'PORTAL_AVOID_SOFT_INPUT_VIEW' as const,
  //
  MULTIPLE_INPUTS_FORM_KEYBOARD_AVOIDING_VIEW: 'MULTIPLE_INPUTS_FORM_KEYBOARD_AVOIDING_VIEW' as const,
  MULTIPLE_INPUTS_FORM_KEYBOARD_AWARE_SCROLL_VIEW: 'MULTIPLE_INPUTS_FORM_KEYBOARD_AWARE_SCROLL_VIEW' as const,
  MULTIPLE_INPUTS_FORM_IQ_KEYBOARD_MANAGER_AND_ADJUST_RESIZE: 'MULTIPLE_INPUTS_FORM_IQ_KEYBOARD_MANAGER+ADJUST_RESIZE' as const,
  MULTIPLE_INPUTS_FORM_AVOID_SOFT_INPUT_MODULE: 'MULTIPLE_INPUTS_FORM_AVOID_SOFT_INPUT_MODULE' as const,
  MULTIPLE_INPUTS_FORM_AVOID_SOFT_INPUT_VIEW: 'MULTIPLE_INPUTS_FORM_AVOID_SOFT_INPUT_VIEW' as const,
};
